### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dingraha** [BYUFLOWLab/CCBlade#32]
@JuliaRegistrator register

**Comment by dingraha** [comment]
Arg, the TagBot workflow failed, sad. Looks like it might be an issue with the SSH deploy key, aka `secrets.DOCUMENTER_KEY`.

**Comment by dingraha** [comment]
@andrewning Thanks for updating the SSH key. 

I tried re-running the TagBot action to get the new release tagged, but it "failed" (still a green checkmark, but no tag happened) with a `No new versions to release` message. I think the reason this happened is related to the value of the `lookback` input in the TagBot.yml file here https://github.com/byuflowlab/CCBlade.jl/blob/b5e95143d086bfa6a5612f90799151430e950cdb/.github/workflows/TagBot.yml#L9 which tells TagBot.yml to look three days in the past to find new releases to tag. Since I reran TagBot today, aka 8 days after the release, TagBot.yml missed the release and didn't actually do anything.

I guess we could temporarily increase `loopback`, but I think the easiest thing to do is to just have someone with write access to `byuflowlab/CCBlade.jl` to run

```
git tag -a v0.2.6 -m "<description of version>" c39af6fb764495f691d1eb57ce0c9bf99f869504
git push origin v0.2.6
```

like the message above suggests (but with `origin` pointing to `byuflowlab/CCBlade.jl` not a fork).

**Comment by andrewning** [comment]
ok done now
